// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Grid = require("./Grid.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var $$Error = require("./Error.js");
var Types = require("./Types.js");
var React = require("react");
var Single = require("./Single.js");
var Spinner = require("./Spinner.js");
var Reducers = require("./reducers.js");
var ReactUpdate = require("reason-react-update/src/ReactUpdate.bs.js");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");

function App(Props) {
  var match = ReactUpdate.useReducer(/* Loading */1, Reducers.appReducer);
  var dispatch = match[1];
  var state = match[0];
  React.useEffect((function () {
          var watcher = ReasonReactRouter.watchUrl((function (url) {
                  return Curry._1(dispatch, /* ChangeRoute */Block.__(6, [Types.Route[/* urlToRoute */0](url)]));
                }));
          Curry._1(dispatch, /* FetchPosts */0);
          return (function (param) {
                    return ReasonReactRouter.unwatchUrl(watcher);
                  });
        }), ([]));
  var navigate = function (route, e) {
    e.preventDefault();
    return ReasonReactRouter.push(Types.Route[/* toUrl */1](route));
  };
  var tmp;
  if (typeof state === "number") {
    tmp = state !== 0 ? React.createElement(Spinner.make, { }) : React.createElement($$Error.make, { });
  } else {
    var posts = state[1];
    var route = state[0];
    tmp = route ? React.createElement(Single.make, {
            posts: posts,
            postId: route[0],
            dispatch: dispatch,
            navigate: navigate
          }) : React.createElement(Grid.make, {
            posts: posts,
            dispatch: dispatch,
            navigate: navigate
          });
  }
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, React.createElement("a", {
                      href: "/",
                      onClick: (function (param) {
                          return navigate(/* Base */0, param);
                        })
                    }, "Catstagram")), tmp);
}

var make = App;

exports.make = make;
/* Grid Not a pure module */
