// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Grid = require("./grid.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var $$Error = require("./error.js");
var Types = require("./Types.js");
var React = require("react");
var Single = require("./single.js");
var Spinner = require("./spinner.js");
var Reducers = require("./reducers.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("App");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var watcher = ReasonReact.Router[/* watchUrl */1]((function (url) {
                      return Curry._1(self[/* send */3], /* ChangeRoute */Block.__(5, [Types.Route[/* urlToRoute */0](url)]));
                    }));
              Curry._1(self[/* send */3], /* FetchPosts */0);
              return Curry._1(self[/* onUnmount */4], (function () {
                            return ReasonReact.Router[/* unwatchUrl */2](watcher);
                          }));
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var send = param[/* send */3];
              var state = param[/* state */1];
              var navigate = function (route, e) {
                e.preventDefault();
                return ReasonReact.Router[/* push */0](Types.Route[/* toUrl */1](route));
              };
              var tmp;
              if (typeof state === "number") {
                tmp = state !== 0 ? ReasonReact.element(undefined, undefined, Spinner.make(/* array */[])) : ReasonReact.element(undefined, undefined, $$Error.make(/* array */[]));
              } else {
                var posts = state[1];
                var route = state[0];
                tmp = route ? ReasonReact.element(undefined, undefined, Single.make(posts, route[0], send, navigate, /* array */[])) : ReasonReact.element(undefined, undefined, Grid.make(posts, send, navigate, /* array */[]));
              }
              return React.createElement("div", undefined, React.createElement("h1", undefined, React.createElement("a", {
                                  href: "/",
                                  onClick: (function (param) {
                                      return navigate(/* Base */0, param);
                                    })
                                }, "Catstagram")), tmp);
            }),
          /* initialState */(function () {
              return /* Loading */1;
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */Reducers.appReducer,
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
