// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Comments");

function make(comments, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "comments"
                        }, React.createElement("div", {
                              className: "comments-list"
                            }, Belt_List.toArray(Belt_List.map(comments, (function (param) {
                                        return React.createElement("div", {
                                                    key: param[/* id */0],
                                                    className: "comment"
                                                  }, React.createElement("p", undefined, React.createElement("strong", undefined, param[/* from */1][/* username */0]), param[/* text */2], React.createElement("button", {
                                                            className: "remove-comment"
                                                          }, "✖️")));
                                      })))), React.createElement("form", {
                              className: "comment-form"
                            }, React.createElement("input", {
                                  placeholder: "author",
                                  type: "text"
                                }), React.createElement("input", {
                                  placeholder: "comment",
                                  type: "text"
                                }), React.createElement("input", {
                                  type: "submit"
                                })));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
