// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Form = require("./form.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Comments");

function make(comments, send, postId, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "comments"
                        }, React.createElement("div", {
                              className: "comments-list"
                            }, Belt_List.toArray(Belt_List.map(comments, (function (param) {
                                        var id = param[/* id */0];
                                        return React.createElement("div", {
                                                    key: id,
                                                    className: "comment"
                                                  }, React.createElement("p", undefined, React.createElement("strong", undefined, param[/* from */1][/* username */0]), param[/* text */2], React.createElement("button", {
                                                            className: "remove-comment",
                                                            onClick: (function () {
                                                                return Curry._1(send, /* DeleteComment */Block.__(4, [
                                                                              postId,
                                                                              id
                                                                            ]));
                                                              })
                                                          }, "✖️")));
                                      })))), ReasonReact.element(undefined, undefined, Form.make((function (author, text) {
                                    return Curry._1(send, /* AddComment */Block.__(3, [
                                                  postId,
                                                  author,
                                                  text
                                                ]));
                                  }), /* array */[])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
