// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Form = require("./form.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");

function Comments(Props) {
  var comments = Props.comments;
  var dispatch = Props.dispatch;
  var postId = Props.postId;
  return React.createElement("div", {
              className: "comments"
            }, React.createElement("div", {
                  className: "comments-list"
                }, Belt_List.toArray(Belt_List.map(comments, (function (param) {
                            var id = param[/* id */0];
                            return React.createElement("div", {
                                        key: id,
                                        className: "comment"
                                      }, React.createElement("p", undefined, React.createElement("strong", undefined, param[/* from */1][/* username */0]), param[/* text */2], React.createElement("button", {
                                                className: "remove-comment",
                                                onClick: (function (_e) {
                                                    return Curry._1(dispatch, /* DeleteComment */Block.__(4, [
                                                                  postId,
                                                                  id
                                                                ]));
                                                  })
                                              }, "✖️")));
                          })))), React.createElement(Form.make, {
                  handleSubmit: (function (author, text) {
                      return Curry._1(dispatch, /* AddComment */Block.__(3, [
                                    postId,
                                    author,
                                    text
                                  ]));
                    })
                }));
}

var make = Comments;

exports.make = make;
/* Form Not a pure module */
