// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function $$Error(Props) {
  return React.createElement("div", {
              className: "spinner"
            }, React.createElement("h1", undefined, "An error occurred! :("));
}

var make = $$Error;

exports.make = make;
/* react Not a pure module */
