// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var extend = ReasonReact.statelessComponent("Error");

function make() {
  return /* record */[
          /* debugName */extend[/* debugName */0],
          /* reactClassInternal */extend[/* reactClassInternal */1],
          /* handedOffState */extend[/* handedOffState */2],
          /* willReceiveProps */extend[/* willReceiveProps */3],
          /* didMount */extend[/* didMount */4],
          /* didUpdate */extend[/* didUpdate */5],
          /* willUnmount */extend[/* willUnmount */6],
          /* willUpdate */extend[/* willUpdate */7],
          /* shouldUpdate */extend[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "centered"
                        }, React.createElement("h1", undefined, "An error occurred! :("));
            }),
          /* initialState */extend[/* initialState */10],
          /* retainedProps */extend[/* retainedProps */11],
          /* reducer */extend[/* reducer */12],
          /* jsElementWrapped */extend[/* jsElementWrapped */13]
        ];
}

exports.extend = extend;
exports.make = make;
/* extend Not a pure module */
