// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Form(Props) {
  var handleSubmit = Props.handleSubmit;
  var match = React.useReducer((function (state, action) {
          if (typeof action === "number") {
            return /* record */[
                    /* author */"",
                    /* comment */""
                  ];
          } else if (action.tag) {
            return /* record */[
                    /* author */state[/* author */0],
                    /* comment */action[0]
                  ];
          } else {
            return /* record */[
                    /* author */action[0],
                    /* comment */state[/* comment */1]
                  ];
          }
        }), /* record */[
        /* author */"",
        /* comment */""
      ]);
  var dispatch = match[1];
  var match$1 = match[0];
  var comment = match$1[/* comment */1];
  var author = match$1[/* author */0];
  return React.createElement("form", {
              className: "comment-form",
              onSubmit: (function (e) {
                  e.preventDefault();
                  Curry._2(handleSubmit, author, comment);
                  return Curry._1(dispatch, /* ClearForm */0);
                })
            }, React.createElement("input", {
                  placeholder: "author",
                  type: "text",
                  value: author,
                  onChange: (function (e) {
                      return Curry._1(dispatch, /* ChangeAuthor */Block.__(0, [e.target.value]));
                    })
                }), React.createElement("input", {
                  placeholder: "comment",
                  type: "text",
                  value: comment,
                  onChange: (function (e) {
                      return Curry._1(dispatch, /* ChangeComment */Block.__(1, [e.target.value]));
                    })
                }), React.createElement("input", {
                  hidden: true,
                  type: "submit"
                }));
}

var make = Form;

exports.make = make;
/* react Not a pure module */
