// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("Form");

function make(handleSubmit, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var send = param[/* send */3];
              var match = param[/* state */1];
              var comment = match[/* comment */1];
              var author = match[/* author */0];
              return React.createElement("form", {
                          className: "comment-form",
                          onSubmit: (function (e) {
                              e.preventDefault();
                              Curry._2(handleSubmit, author, comment);
                              return Curry._1(send, /* ClearForm */0);
                            })
                        }, React.createElement("input", {
                              placeholder: "author",
                              type: "text",
                              value: author,
                              onChange: (function (e) {
                                  return Curry._1(send, /* ChangeAuthor */Block.__(0, [e.target.value]));
                                })
                            }), React.createElement("input", {
                              placeholder: "comment",
                              type: "text",
                              value: comment,
                              onChange: (function (e) {
                                  return Curry._1(send, /* ChangeComment */Block.__(1, [e.target.value]));
                                })
                            }), React.createElement("input", {
                              hidden: true,
                              type: "submit"
                            }));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* author */"",
                      /* comment */""
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                return /* Update */Block.__(0, [/* record */[
                            /* author */"",
                            /* comment */""
                          ]]);
              } else if (action.tag) {
                return /* Update */Block.__(0, [/* record */[
                            /* author */state[/* author */0],
                            /* comment */action[0]
                          ]]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* author */action[0],
                            /* comment */state[/* comment */1]
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
