// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Post = require("./Post.js");
var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");

function Grid(Props) {
  var posts = Props.posts;
  var dispatch = Props.dispatch;
  var navigate = Props.navigate;
  return React.createElement("div", {
              className: "photo-grid"
            }, Belt_List.toArray(Belt_List.map(posts, (function (post) {
                        return React.createElement(Post.make, {
                                    post: post,
                                    dispatch: dispatch,
                                    navigate: navigate,
                                    key: post[/* id */0]
                                  });
                      }))));
}

var make = Grid;

exports.make = make;
/* Post Not a pure module */
