// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Hashtag(Props) {
  var text = Props.text;
  return React.createElement("a", {
              href: "https://www.instagram.com/explore/tags/" + text,
              target: "blank"
            }, "#" + text);
}

var make = Hashtag;

exports.make = make;
/* react Not a pure module */
