// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var App = require("./app.bs.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

((require("./index.css")));

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App.make("Welcome to Reason Catstagram!", /* array */[])), "root");

console.log("hello world");

/*  Not a pure module */
