// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var App = require("./App.js");
var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");

((require("./index.css")));

ReactDOMRe.renderToElementWithId(React.createElement(App.make, { }), "root");

/*  Not a pure module */
