// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Spinner(Props) {
  return React.createElement("div", {
              className: "spinner"
            }, React.createElement("div", undefined), React.createElement("div", undefined), React.createElement("div", undefined), React.createElement("div", undefined));
}

var make = Spinner;

exports.make = make;
/* react Not a pure module */
