// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function fromJson(json) {
  return /* record */[/* text */Json_decode.field("text", Json_decode.string, json)];
}

var Caption = /* module */[/* fromJson */fromJson];

function fromJson$1(json) {
  return /* record */[/* count */Json_decode.field("count", Json_decode.$$int, json)];
}

var Num = /* module */[/* fromJson */fromJson$1];

function fromJson$2(json) {
  return /* record */[/* url */Json_decode.field("url", Json_decode.string, json)];
}

var Resolution = /* module */[/* fromJson */fromJson$2];

function fromJson$3(json) {
  return /* record */[/* standard_resolution */Json_decode.field("standard_resolution", fromJson$2, json)];
}

var Images = /* module */[/* fromJson */fromJson$3];

function fromJson$4(json) {
  return /* record */[/* username */Json_decode.field("username", Json_decode.string, json)];
}

var From = /* module */[/* fromJson */fromJson$4];

function fromJson$5(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.string, json),
          /* from */Json_decode.field("from", fromJson$4, json),
          /* text */Json_decode.field("text", Json_decode.string, json),
          /* created_time */Json_decode.field("created_time", Json_decode.string, json)
        ];
}

function decodeComments(json) {
  return Json_decode.field("data", (function (param) {
                return Json_decode.list(fromJson$5, param);
              }), json);
}

var Comment = /* module */[
  /* fromJson */fromJson$5,
  /* decodeComments */decodeComments
];

function fromJson$6(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.string, json),
          /* caption */Json_decode.field("caption", fromJson, json),
          /* images */Json_decode.field("images", fromJson$3, json),
          /* likes */Json_decode.field("likes", fromJson$1, json),
          /* num_comments */Json_decode.field("comments", fromJson$1, json),
          /* user_has_liked */Json_decode.field("user_has_liked", Json_decode.bool, json),
          /* comments : [] */0
        ];
}

function decodePosts(json) {
  return Json_decode.field("data", (function (param) {
                return Json_decode.list(fromJson$6, param);
              }), json);
}

var Post = /* module */[
  /* fromJson */fromJson$6,
  /* decodePosts */decodePosts
];

exports.Caption = Caption;
exports.Num = Num;
exports.Resolution = Resolution;
exports.Images = Images;
exports.From = From;
exports.Comment = Comment;
exports.Post = Post;
/* No side effect */
