// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Random = require("bs-platform/lib/js/random.js");
var $$String = require("bs-platform/lib/js/string.js");

function toHex(x) {
  var _acc = /* [] */0;
  var _x = x;
  while(true) {
    var x$1 = _x;
    var acc = _acc;
    var division = x$1 / 16;
    var result = Math.floor(division);
    var remainder = (division - result) * 16;
    var stringRemainder = String(remainder | 0);
    var match = result === 0;
    if (match) {
      return $$String.concat("", /* :: */[
                  stringRemainder,
                  acc
                ]);
    } else {
      _x = result;
      _acc = /* :: */[
        stringRemainder,
        acc
      ];
      continue ;
    }
  };
}

function s4() {
  return toHex(Math.floor((1 + Random.$$float(1)) * 65536)).substr(1);
}

function make() {
  return s4(/* () */0) + (s4(/* () */0) + ("-" + (s4(/* () */0) + ("-" + (s4(/* () */0) + ("-" + (s4(/* () */0) + ("-" + (s4(/* () */0) + (s4(/* () */0) + s4(/* () */0)))))))))));
}

exports.toHex = toHex;
exports.s4 = s4;
exports.make = make;
/* No side effect */
