// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Js_math = require("bs-platform/lib/js/js_math.js");

function s4() {
  var arg = Js_math.floor((1 + Math.random()) * 65536).toString(16);
  return (function (param) {
              return arg.substr(param);
            })(1);
}

function make() {
  return s4(/* () */0) + (s4(/* () */0) + ("-" + (s4(/* () */0) + ("-" + (s4(/* () */0) + ("-" + (s4(/* () */0) + ("-" + (s4(/* () */0) + (s4(/* () */0) + s4(/* () */0)))))))))));
}

exports.s4 = s4;
exports.make = make;
/* No side effect */
